<?
include("CONNECTIONFILE_3K45jd2DMD1.php");
if(!(@mysql_connect("$host","$user","$pass") && @mysql_select_db("$tablename"))) {?>Geen verbinding...<?}
    $dbres                              = mysql_query("SELECT * FROM `cron`");
    while($x = mysql_fetch_object($dbres))
      $update[$x->name]         = $x->time;
    if(floor($update['hour']/3600) <= floor(time()/3600)) {
      $dbres                            = mysql_query("SELECT GET_LOCK('hour_update',0)");
      if(mysql_result($dbres,0) == 1) {
        $cron_pass                      = "secretcronpassword";
        mysql_query("SELECT RELEASE_LOCK('hour_update')");
$datum1 = (date("Y-m-d H"));
$datum = time()+3600;
mysql_query("UPDATE `cron` SET `time`='$datum' WHERE `name`='hour'");
$drank1 = rand(250,350);
$drank2 = rand(250,350);
$drank3 = rand(250,350);
$drank4 = rand(250,350);
$drank5 = rand(250,350);
$drank6 = rand(250,350);
$nederwietrand1 = rand(600,1300);
$nederwietrand2 = rand(600,1300);
$nederwietrand3 = rand(600,1300);
$nederwietrand4 = rand(600,1300);
$nederwietrand5 = rand(600,1300);
$nederwietrand6 = rand(600,1300);
$paddorand1 = rand(1500,2200);
$paddorand2 = rand(1500,2200);
$paddorand3 = rand(1500,2200);
$paddorand4 = rand(1500,2200);
$paddorand5 = rand(1500,2200);
$paddorand6 = rand(1500,2200);
$xtcrand1 = rand(2500,3100);
$xtcrand2 = rand(2500,3100);
$xtcrand3 = rand(2500,3100);
$xtcrand4 = rand(2500,3100);
$xtcrand5 = rand(2500,3100);
$xtcrand6 = rand(2500,3100);
$lsdrand1 = rand(3400,4000);
$lsdrand2 = rand(3400,4000);
$lsdrand3 = rand(3400,4000);
$lsdrand4 = rand(3400,4000);
$lsdrand5 = rand(3400,4000);
$lsdrand6 = rand(3400,4000);
$speedrand1 = rand(4000,4600);
$speedrand2 = rand(4000,4600);
$speedrand3 = rand(4000,4600);
$speedrand4 = rand(4000,4600);
$speedrand5 = rand(4000,4600);
$speedrand6 = rand(4000,4600);
$opiumrand1 = rand(4500,5000);
$opiumrand2 = rand(4500,5000);
$opiumrand3 = rand(4500,5000);
$opiumrand4 = rand(4500,5000);
$opiumrand5 = rand(4500,5000);
$opiumrand6 = rand(4500,5000);
$pruimtabak1 = rand(600,1300);
$pruimtabak2 = rand(600,1300);
$pruimtabak3 = rand(600,1300);
$pruimtabak4 = rand(600,1300);
$pruimtabak5 = rand(600,1300);
$pruimtabak6 = rand(600,1300);
$vannelle1 = rand(1500,2200);
$vannelle2 = rand(1500,2200);
$vannelle3 = rand(1500,2200);
$vannelle4 = rand(1500,2200);
$vannelle5 = rand(1500,2200);
$vannelle6 = rand(1500,2200);
$drum1 = rand(2500,3100);
$drum2 = rand(2500,3100);
$drum3 = rand(2500,3100);
$drum4 = rand(2500,3100);
$drum5 = rand(2500,3100);
$drum6 = rand(2500,3100);
$lm1 = rand(3400,4000);
$lm2 = rand(3400,4000);
$lm3 = rand(3400,4000);
$lm4 = rand(3400,4000);
$lm5 = rand(3400,4000);
$lm6 = rand(3400,4000);
$kent1 = rand(4000,4600);
$kent2 = rand(4000,4600);
$kent3 = rand(4000,4600);
$kent4 = rand(4000,4600);
$kent5 = rand(4000,4600);
$kent6 = rand(4000,4600);
$panter1 = rand(4500,5000);
$panter2 = rand(4500,5000);
$panter3 = rand(4500,5000);
$panter4 = rand(4500,5000);
$panter5 = rand(4500,5000);
$panter6 = rand(4500,5000);
mysql_query("UPDATE `stad` SET `drankp`='$drank1' WHERE `stad`='1'");
mysql_query("UPDATE `stad` SET `drankp`='$drank2' WHERE `stad`='2'");
mysql_query("UPDATE `stad` SET `drankp`='$drank3' WHERE `stad`='3'");
mysql_query("UPDATE `stad` SET `drankp`='$drank4' WHERE `stad`='4'");
mysql_query("UPDATE `stad` SET `drankp`='$drank5' WHERE `stad`='5'");
mysql_query("UPDATE `stad` SET `drankp`='$drank6' WHERE `stad`='6'");
mysql_query("UPDATE `drugskoers` SET `nederwiet`='$nederwietrand1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `nederwiet`='$nederwietrand2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `nederwiet`='$nederwietrand3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `nederwiet`='$nederwietrand4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `nederwiet`='$nederwietrand5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `nederwiet`='$nederwietrand6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `paddo`='$paddorand1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `paddo`='$paddorand2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `paddo`='$paddorand3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `paddo`='$paddorand4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `paddo`='$paddorand5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `paddo`='$paddorand6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `xtc`='$xtcrand1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `xtc`='$xtcrand2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `xtc`='$xtcrand3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `xtc`='$xtcrand4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `xtc`='$xtcrand5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `xtc`='$xtcrand6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `lsd`='$lsdrand1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `lsd`='$lsdrand2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `lsd`='$lsdrand3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `lsd`='$lsdrand4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `lsd`='$lsdrand5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `lsd`='$lsdrand6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `speed`='$speedrand1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `speed`='$speedrand2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `speed`='$speedrand3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `speed`='$speedrand4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `speed`='$speedrand5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `speed`='$speedrand6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `opium`='$opiumrand1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `opium`='$opiumrand2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `opium`='$opiumrand3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `opium`='$opiumrand4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `opium`='$opiumrand5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `opium`='$opiumrand6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `pruimtabak`='$pruimtabak1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `pruimtabak`='$pruimtabak2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `pruimtabak`='$pruimtabak3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `pruimtabak`='$pruimtabak4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `pruimtabak`='$pruimtabak5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `pruimtabak`='$pruimtabak6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `vannelle`='$vannelle1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `vannelle`='$vannelle2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `vannelle`='$vannelle3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `vannelle`='$vannelle4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `vannelle`='$vannelle5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `vannelle`='$vannelle6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `drum`='$drum1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `drum`='$drum2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `drum`='$drum3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `drum`='$drum4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `drum`='$drum5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `drum`='$drum6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `lm`='$lm1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `lm`='$lm2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `lm`='$lm3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `lm`='$lm4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `lm`='$lm5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `lm`='$lm6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `kent`='$kent1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `kent`='$kent2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `kent`='$kent3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `kent`='$kent4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `kent`='$kent5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `kent`='$kent6' WHERE `land`='6'");
mysql_query("UPDATE `drugskoers` SET `panter`='$panter1' WHERE `land`='1'");
mysql_query("UPDATE `drugskoers` SET `panter`='$panter2' WHERE `land`='2'");
mysql_query("UPDATE `drugskoers` SET `panter`='$panter3' WHERE `land`='3'");
mysql_query("UPDATE `drugskoers` SET `panter`='$panter4' WHERE `land`='4'");
mysql_query("UPDATE `drugskoers` SET `panter`='$panter5' WHERE `land`='5'");
mysql_query("UPDATE `drugskoers` SET `panter`='$panter6' WHERE `land`='6'");
mysql_query("UPDATE `users` SET `safe`=`safe`-'1' WHERE `safe`>'0'");
mysql_query("UPDATE `users` SET `maffia`=`maffia`-'1' WHERE `maffia`>'0'");
mysql_query("UPDATE `users` SET `safe`='0' WHERE `safe`<'0'");
mysql_query("UPDATE `users` SET `maffia`='0' WHERE `maffia`<'0'");
mysql_query("UPDATE `users` SET `aangevallen`='0'");
mysql_query("UPDATE `users` SET `bank`=`bank`+`hoerenhuis`*'500'");
mysql_query("UPDATE `users` SET `contant`=`contant`+'250',`bank`=`bank`+'250' WHERE UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(`online`) < 300");
mysql_query("UPDATE `users` SET `banpunten`=`banpunten`-'1' WHERE `banpunten`>'0'");
mysql_query("UPDATE `users` SET `forumbanpunten`=`forumbanpunten`-'1' WHERE `forumbanpunten`>'0'");
$geld                		= $data2->hoeren;
$geld2                      = $geld*5;
$geld3               		= $data2->hoerenwerkend;
$geld4                      = $geld*15;
$geld5                      = $geld4+$geld2;
$inkomen                    = $geld5;
mysql_query("UPDATE `users` SET `bank`=`bank`+'$inkomen' WHERE `hoeren`>'0'");
mysql_query("UPDATE `users` SET `hoerpimped`='0'");
}}?>
