<?
include("config.php");
if(isset($_POST['reset']) && $data->admin > 0){echo"<font color='red'>Het spel is gereset!<BR><BR><BR></font>";
mysql_query("UPDATE `users` SET `contant`='20000'");
mysql_query("UPDATE `users` SET `bank`='100000'");
mysql_query("UPDATE `users` SET `killers`='0'");
mysql_query("UPDATE `users` SET `rank`='1'");
mysql_query("UPDATE `users` SET `health`='100'");
mysql_query("UPDATE `users` SET `bankleft`='15'");
mysql_query("UPDATE `users` SET `power`='0'");
if(isset($_POST['all'])){
mysql_query("UPDATE `users` SET `callcredits`='0'");
mysql_query("UPDATE `users` SET `vipdays`='0'");
mysql_query("UPDATE `users` SET `maffia`='0'");
mysql_query("UPDATE `users` SET `bankstandard`='15'");
mysql_query("UPDATE `users` SET `dagenrente`='0'");
mysql_query("UPDATE `users` SET `maxaccounts`='0'");
}
mysql_query("UPDATE `users` SET `city`='1'");
mysql_query("UPDATE `users` SET `familie`=''");
mysql_query("UPDATE `users` SET `rankvord`='0'");
mysql_query("UPDATE `users` SET `safe`='12'");
mysql_query("UPDATE `users` SET `respect`='0'");
mysql_query("UPDATE `users` SET `geefeer`='0'");
mysql_query("UPDATE `users` SET `kogels`='0'");
mysql_query("UPDATE `users` SET `attwins`='0'");
mysql_query("UPDATE `users` SET `attlost`='0'");
mysql_query("UPDATE `users` SET `bankpas`='0'");
mysql_query("UPDATE `users` SET `kluis`='0'");
mysql_query("UPDATE `users` SET `zwitserse`='0'");
mysql_query("UPDATE `users` SET `deagle`='0'");
mysql_query("UPDATE `users` SET `pepperspray`='0'");
mysql_query("UPDATE `users` SET `knuppel`='0'");
mysql_query("UPDATE `users` SET `sigp`='0'");
mysql_query("UPDATE `users` SET `c4`='0'");
mysql_query("UPDATE `users` SET `m16`='0'");
mysql_query("UPDATE `users` SET `cornershot`='0'");
mysql_query("UPDATE `users` SET `pitbull`='0'");
mysql_query("UPDATE `users` SET `sniper`='0'");
mysql_query("UPDATE `users` SET `swatgun`='0'");
mysql_query("UPDATE `users` SET `bazooka`='0'");
mysql_query("UPDATE `users` SET `bodyguards`='0'");
mysql_query("UPDATE `users` SET `warboot`='0'");
mysql_query("UPDATE `users` SET `atoombom`='0'");
mysql_query("UPDATE `users` SET `tank`='0'");
mysql_query("UPDATE `users` SET `scud`='0'");
mysql_query("UPDATE `users` SET `satteliet`='0'");
mysql_query("UPDATE `users` SET `spacestation`='0'");
mysql_query("UPDATE `users` SET `hoerenhuis`='0'");
mysql_query("UPDATE `users` SET `switchblade`='0'");
mysql_query("UPDATE `users` SET `bezitiets`='0'");
mysql_query("UPDATE `users` SET `vermoord`='0'");
mysql_query("UPDATE `users` SET `vakantie`='0'");
mysql_query("UPDATE `users` SET `famlevel`='0'");
mysql_query("UPDATE `users` SET `hoofdwaarde`='0'");
mysql_query("UPDATE `users` SET `moordenaar`=''");
mysql_query("UPDATE `users` SET `moordpremie`=''");
mysql_query("UPDATE `users` SET `moorddatum`=''");
mysql_query("UPDATE `users` SET `vordering`='0'");
mysql_query("UPDATE `users` SET `killcount`='0'");
mysql_query("UPDATE `users` SET `drugsmax`='1'");
mysql_query("UPDATE `users` SET `nederwietupgr`='0'");
mysql_query("UPDATE `users` SET `paddoupgr`='0'");
mysql_query("UPDATE `users` SET `xtcupgr`='0'");
mysql_query("UPDATE `users` SET `lsdupgr`='0'");
mysql_query("UPDATE `users` SET `speedupgr`='0'");
mysql_query("UPDATE `users` SET `opiumupgr`='0'");
mysql_query("UPDATE `users` SET `nederwiet`='0'");
mysql_query("UPDATE `users` SET `paddo`='0'");
mysql_query("UPDATE `users` SET `xtc`='0'");
mysql_query("UPDATE `users` SET `lsd`='0'");
mysql_query("UPDATE `users` SET `speed`='0'");
mysql_query("UPDATE `users` SET `opium`='0'");
mysql_query("UPDATE `users` SET `kluisgeld`='0'");
mysql_query("UPDATE `users` SET `zwitsersegeld`='0'");
mysql_query("UPDATE `users` SET `zwitsersehalen`='50000000'");
mysql_query("UPDATE `users` SET `zwitsersestorten`='5000000'");
mysql_query("UPDATE `users` SET `aankomst`=''");
mysql_query("UPDATE `users` SET `draaitijd`='000-00-00 00:00:00'");
mysql_query("UPDATE `users` SET `hlronde`='1'");
mysql_query("UPDATE `users` SET `hltijd`='000-00-00 00:00:00'");
mysql_query("UPDATE `users` SET `roulette`='0'");
mysql_query("UPDATE `users` SET `aangevallen`='0'");
mysql_query("UPDATE `users` SET `missionsfixed`=''");
mysql_query("DELETE FROM `autos`");
mysql_query("DELETE FROM `clicks`");
mysql_query("DELETE FROM `contacts` WHERE `owner`='' OR `person`=''");
mysql_query("DELETE FROM `contracten`");
mysql_query("DELETE FROM `families`");
mysql_query("DELETE FROM `gastenboek`");
mysql_query("DELETE FROM `hitlist`");
mysql_query("DELETE FROM `messages`");
mysql_query("DELETE FROM `veilinglogs`");
mysql_query("UPDATE `station` SET `eigenaar`='', `laatstebod`='0', `laatstebieder`=''");
mysql_query("UPDATE `vliegveld` SET `eigenaar`='', `laatstebod`='0', `laatstebieder`=''");
}
if($data->admin < 1){?>Jij hebt geen toegang om het spel te resetten!<?}else{?>
<form method="POST">
<input type="radio" name="all"> Ik wil ook callcredits E.D resetten<BR><BR>
<input type="submit" name="reset" value="Reset het hele spel!">
</form><?}?>
